# Generated by Django 3.2.11 on 2022-01-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20220116_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
